### ISSUE TITLE
ODRL Best Practices document needs corrections and add-ons

### ISSUE THREAD

**Issue by nitmws** [w3c/odrl#1]
These comments are based on the [ODRL BP document](https://w3c.github.io/odrl/bp/) version of 19 March 2018.
And I'm aware that the document is Under Construction and I point only at issues regarding the existing data, not at missing things (with an exception in 2 below).

1. General: all examples using an action different from "use" or "transfer" must have a profile - but they don't have one
2. Based on 1.: the use of profiles should be explained
-- how to add one to many profile ids
-- how to add one to many JSON-LD file links to @context 
3. General: the numbering of sections breaks below 3. - the following 1 should be 3.1 etc4. re section 1.2: the narrative talks about a photo, the asset id makes one think about a movie
5. Example 1.2A shows https://www.wikidata.org/wiki/Q183 as id for Germany. But that's the URL of the Wikidata page providing information about this entity, the ID of Germany as Wikidata entity is https://www.wikidata.org/entity/Q183 - see "concept URI" on https://www.wikidata.org/wiki/Wikidata:Data_access
6. Example 1.2A shows a "comment" property of constraint - but the odrl.jsonld does not map this property name to an id. This way "comment" is invalid.
6. Examples 1.2B and 1.2C: to comply with the narrative the operator of the dateTime constraint should be gteq. (Currently the permitted display starts on 2 January 2019.)
7. re "7 How to generalize action" - diagram: it shows "transfer" as narrower term of "use" - but they must be siblings at the top level.

It's ok for me to contribute to fixing these issues.

**Comment by vroddon** [comment]
I am not sure about how to implement every change proposed by Michael, but I will try to do it before the next telco.

**Comment by vroddon** [comment]
Sections have been renumbered.
NO need of profile for the actions used in the document.
