### ISSUE TITLE
Access and License Indicators (ALI)

### ISSUE THREAD

**Issue by vroddon** [w3c/odrl#14]
We have been contacted as per ALI
https://www.niso.org/niso-io/2020/10/help-us-update-recommended-practice-access-and-license-indicators-ali
However, we have no more details. 

I create this issue for its discussion in the next meeting...

**Comment by riannella** [comment]
Original email:

Hello,
 
I hope this day finds you well. I am a member of a working group at NISO helping to update the Access & License Indicators recommendation. There is some information about the working group at https://www.niso.org/niso-io/2020/10/help-us-update-recommended-practice-access-and-license-indicators-ali and I would be glad to share more information. The reason for this email is that I am researching ODRL for its potential to help with certain use cases. It looks like ODRL is able to support the use cases that we are trying to address. However, it also looks like a system that processes ODRL would need to be very complex unless only a subset of ODRL is being used. I want to ensure that the recommendation for ALI can be implemented by a developer with commonly available skills. The purpose of this email is to start a conversation and find out where to ask questions and get help. Do you have any general advice on how to make implementing ODRL easy, and what is the best way to ask for help regarding ODRL?
 
Thank you,
Vincent
 
______________________________________________
Vincent M. Lizzi
Head of Information Standards | Taylor & Francis Group
530 Walnut St., Suite 850, Philadelphia, PA 19106
E-Mail: vincent.lizzi@taylorandfrancis.com
Web: www.tandfonline.com
 
Taylor & Francis is a trading name of Informa UK Limited,
registered in England under no. 1072954
 
"Everything should be made as simple as possible, but not simpler."
 

Information Classification: General

**Comment by riannella** [comment]
See response https://lists.w3.org/Archives/Public/public-odrl/2021Apr/0002.html

**Comment by riannella** [comment]
Email send 9/8/24 to Vincent asking for followup actions...

**Comment by riannella** [comment]
Closing issue as no response received

**Comment by vincentml** [comment]
Hi @riannella 

My apologies for not responding sooner. The NISO ALI working group has finished its work. The working group chose to retain compatibility with the previous version of ALI and make only minor changes to add required features, and ODRL was deemed out of scope. 

It may be of interest that ODRL was used in a related project, STM's Article Sharing Framework, to include machine readable metadata in HTML.

Thank you,
Vincent
