### ISSUE TITLE
Publication of ODRL Profiles

### ISSUE THREAD

**Issue by riannella** [w3c/odrl#17]
1. Publication of profiles
There should be an ODRL landing page for the profiles, an index. Apart from those in this namespace (https://w3c.github.io/odrl/profile-bigdata/), there may be other external --at least we have produced two.
- ODRL profile for Language Resources http://purl.org/odrl-lr (edited by UPM Madrid and ILSP Athens)
- ODRL profile for Access Control in Solid https://protect.oeg.fi.upm.es/odrl-access-control-profile/oac.html (edited by UPM Madrid and ADAPT Dublin)

If we want to have them as drafts in URIs such as https://w3c.github.io/odrl/profile-language/, I guess we should discuss them in the general call. Am I wrong? We are interested in the Language Resources case, not so much for the Access Control in Solid --other platforms such as the European Language Grid, Metashare and some Clarin nodes may use them in the next few monts, and they would rather have a more neutral space. I am now in Athens working on this actually...

**Comment by riannella** [comment]
9) Publication of ODRL Profiles
- Added new Profiles at: https://www.w3.org/community/odrl/profile/

**Comment by bact** [comment]
Some more Profiles at https://www.w3.org/community/odrl/wiki/ODRL_Profiles

**Comment by riannella** [comment]
Profiles pages are now setup ok
