### ISSUE TITLE
Typo on ODRL Implementation Best Practices

### ISSUE THREAD

**Issue by lolostar** [w3c/odrl#25]
Hi,

There is a typo in 4. Sample ODRL policies - Example 1

      odrl:permission
      [ 
         odrl:action odrl:distribute , odrl:modify , odrl:reproduce         **;      # <-** 
	     odrl:duty
		 [   
		    odrl:action cc:Notice , cc:ShareAlike
		 ] ;
	  ] ;

Regards

**Comment by riannella** [comment]
thanks @lolostar 
Will add to the errata list

**Comment by vroddon** [comment]
Fixed as per b2cacb1918eeb25806c3c6715264e06fca2fdda3
