### ISSUE TITLE
Connect `odrl:Agreement` with an `odrl:Offer` and an `odrl:Request` that originated the agreement

### ISSUE THREAD

**Issue by besteves4** [w3c/odrl#29]
Hi.

Are there any guidelines or recommended vocabulary terms (from ODRL or from other vocabs) to connect an `odrl:Agreement` with other policies?

The use-case I have in mind is the following:
A party publishes an `odrl:Offer` policy for the target data `http://example.com/asset:1` and a second party makes an `odrl:Request` to that asset. The parties reach an agreement which is recorded using an `odrl:Agreement`. What properties (represented in the example below with `<has offer>` and `<has request>`) should be used to connect the agreement with the offer and the request that originated it? 
```
:offer a odrl:Offer .
:request a odrl:Request .
:agreement a odrl:Agreement ;
        <has offer> :offer ;
        <has request> :request .
```

**Comment by riannella** [comment]
The ODRL model 'metadata' section: https://www.w3.org/TR/odrl-model/#metadata
recommends the DCMI properties for this.

`dct:references` could be used in your use case?
(as we now the types of the resources, a single property would suffice)

**Comment by besteves4** [comment]
Fair enough! I will add this example to the "ODRL Implementation Best Practices" document as I know I am not the only one that had this question. Thanks @riannella
