### ISSUE TITLE
A typo error in section 2.6 Rule Class

### ISSUE THREAD

**Issue by ksridhar** [w3c/odrl#36]
In the section https://www.w3.org/TR/odrl-model/#rule

The sentence
Explicit sub-properties of the abstract relation, **relation** and failure properties must be used, the choice depending on the subclass of Rule in question.

Should have been 
Explicit sub-properties of the abstract relation, **function** and failure properties must be used, the choice depending on the subclass of Rule in question.

**Comment by riannella** [comment]
Moved to https://github.com/w3c/poe/issues/308
