### ISSUE TITLE
Invalid json-ld syntax in EXAMPLE 29 

### ISSUE THREAD

**Issue by ksridhar** [w3c/odrl#38]
The json-ld instance presented in EXAMPLE 29  in section https://www.w3.org/TR/odrl-model/#composition-compact is invalid.
There is a trailing '`,`' (comma) after the second `"action: : "play"`.
This was checked using [json-lint](https://jsonlint.com/) and [rdf-converter](https://issemantic.net/rdf-converter).
The former reported
```
Invalid JSON!
Error: Parse error on line 16:
...n": "play",        }]}  
----------------------^
Expecting 'STRING', got '}'
```

**Comment by riannella** [comment]
Copied to https://github.com/w3c/poe/issues/310
