### ISSUE TITLE
Wrong naming of the ``neq`` operator 

### ISSUE THREAD

**Issue by IcarusCoding** [w3c/odrl#40]
The ``neq`` operator is named ``neg`` in the standard document: https://www.w3.org/ns/odrl.jsonld.
The specification clearly states it should be named ``neq``:
![image](https://github.com/w3c/odrl/assets/50166985/4166aa0f-8ab1-4edc-ad8f-5ec294b52c2e)

**Comment by riannella** [comment]
Moved to https://github.com/w3c/poe/issues/311
