### ISSUE TITLE
Feedback on 'ODRL V2.2 Profile Best Practices'

### ISSUE THREAD

**Issue by YassirSellami** [w3c/odrl#41]
Just a few typos:

- `seqence` in the last sentence of **4.**
- `uniqe` in the title of **6.1**

More personal opinions:

- As someone interested into definining a new Constraint, I did not find a description in **4.x What an ODRL Profile can define**
- In **4.9**, maybe there is a better way to handle the paragraph: _It is not required to create a new subclass of Policy for this purpose…_ instead of the repetition several times.
- In **4.10 Example 10** I found that the use case of the example not completely clear.

**Comment by riannella** [comment]
Fixed the typos

**Comment by riannella** [comment]
Thanks Yassir.  We will see if there is any feedback on this new section
