### ISSUE TITLE
Refine refinements

### ISSUE THREAD

**Issue by joshcornejo** [w3c/odrl#42]
In [section 2.5](https://www.w3.org/TR/odrl-model/#constraint), the diagram:

![image](https://github.com/w3c/odrl/assets/10956002/1962089e-161c-4b1f-8985-74f17de81be1)

The relationship "refinement" from [Party Collection | Asset Collection | Action ] implies a bounded relationship between the target/assignee/action and the constraint/logical constraint. 

Since applying the Constraint is inherent to the Rule defining/using it (only applicable in the context of the Rule?), the relationship between the source/action, Rule, and the Constraint should (for clarity) be separated.

I propose that a better illustration of the relationship is (illustrating with the party collection):

```
Rule -----> [Refinement] ---> [ Party Collection ]
                                   |-----------> [ Constraint ]]
                                   |                ^      ^
                                   |                |      |   
                                   └-----------> [ Logical Constraint ]]
```

_(IMHO, would recommend to create more examples with explicit naming references to nodes, having only implicit names and unravelled definitions might mislead the reader)._

**Comment by riannella** [comment]
Hi @joshcornejo - are you proposing an errata for the ODRL Information Model recommendation?

**Comment by riannella** [comment]
Moved to the POE issue list...
https://github.com/w3c/poe/issues/312
