### ISSUE TITLE
Keep meeting notes in the repository

### ISSUE THREAD

**Issue by besteves4** [w3c/odrl#47]
Hi.
To avoid issues in the meeting notes (as I mention [here](https://lists.w3.org/Archives/Public/public-odrl/2024Mar/0011.html)), I suggest we create a folder in this repository to keep one file with notes per meeting we have, and not send it through the mailing list.
That way, if anything needs to be corrected we can easily do it and we can also review last month's meeting notes as the first topic in each meeting to ensure that everyone is ok with what is recorded there.

**Comment by riannella** [comment]
That sounds like a good idea.
Lets start this from the next meeting...
Can you setup a Template so we can copy from meeting to meeting?

**Comment by riannella** [comment]
Shall will  include the Meeting Agenda as well in these notes?
 (ie move away from the Github Meeting Project)

**Comment by besteves4** [comment]
@riannella PR with a proposed template: https://github.com/w3c/odrl/pull/49

**Comment by besteves4** [comment]
Hi @riannella I assume that from now on you and the other chairs will prepare the meeting notes for the calls.
So I think we can close this issue.

**Comment by riannella** [comment]
Yes...thanks!!
