### ISSUE TITLE
Update the CG Home Page

### ISSUE THREAD

**Issue by riannella** [w3c/odrl#5]
Update Implementors/developers page with V2.2 info 

Update Profiles page (order by version)

Remove the Draft CC Profile from the Reports list

**Comment by vroddon** [comment]
I have started editing https://www.w3.org/community/odrl/implementations/, but:
- Was there any public resource/page published by Thomson Reuters?
- Which is the public page for IPTC implementation? I remember a very nice diagram of the evaluator by @nitmws, but I have not found it again...  Still available?

Also, perhaps we may start a https://www.w3.org/community/odrl/implementations/developers/ page with additional links...

**Comment by vroddon** [comment]
Shall we remove this page then?
I have not found how to remove the link but keep the page (just in case...)...
Are we sure we want to delete the page?

![image](https://user-images.githubusercontent.com/5434597/43691827-14b7fcee-9965-11e8-92fa-823a989ea4ff.png)

**Comment by nitmws** [comment]
@vroddon re your IPTC related question:

- All around implementing RightsML is here: http://dev.iptc.org/RightsML. BUT: it is not fully updated yet, only the examples in the pages below http://dev.iptc.org/RightsML-Implementation-Examples have been fully updated to ODRL 2.2 and RightsML 2.0.
- The PDF with the guideline for evaluating ODRL documents is there: https://www.iptc.org/std-dev/RightsML/2018.1/tools/ODRL_GenericRuleEvaluationFlow_3.pdf

Note: I have updated the ODRL page about the RightsML profile: https://www.w3.org/community/odrl/profile/rightsml/

**Comment by nitmws** [comment]
Re Update Profiles page (order by version)
Remove the Draft CC Profile from the Reports list

1. We need a list of profiles on this page https://www.w3.org/community/odrl/profile/ - as it has no sidebar with "child-pages"
2. We should clarify how to use versions in this context:
- should it show the ODRL and the profile version, or only a single one (which one, in this case)?#
- should a specific profile get individual pages for each version of if all versions should be shown on a single page.
3. I went over the existing profile pages:
**  IPTC: has no version number in the title. Updated the content to RightsML 2.0/ODRL 2.2
** Creative Commons: it is of 2012 and tells that a draft based on ODRL 2.1 is open for comments. How to proceed? Is it the power of this CG to close such an invitation for comments?
** Linked Data: tells about actions in 2015. Does anybody know about any progress on that topic?
** OMA: is based on ODRL 1.1 - but may be still in use.

**Comment by riannella** [comment]
I've made all the old V2 pages "draft" so they no longer appear on the front page (on the right).
I need to ask W3C how to remove the draft ODRL V1.1 CC Profile from the left-hand list.
I've created two sections now for Profiles (based on the versions).
We an add a new page (under V2.2) for each new profile created.
