### ISSUE TITLE
W3C TPAC 2024 - Community Group meetings

### ISSUE THREAD

**Issue by riannella** [w3c/odrl#57]
Dear Community Groups,

TPAC 2024 [1] will be held from 23 to 27 September 2024, with a main in-person hub at Hilton Anaheim Hotel, in Anaheim, CA, USA.

As last year, we are adapting our format to build a dynamic meeting.

Here is the projected schedule:
* Monday 23 September: Group meetings
* Tuesday 24 September:
    o Group meetings all day
    o AC plenary sessions in the afternoon
* Wednesday 25 September:
    o Breakout sessions
    o W3C@30 celebration
* Thursday 26 September: Group meetings
* Friday 27 September: Group meetings

We will work with fixed time-slots. Each group will be able to ask for 90 minute and/or 2-hour slots.
We are planning for all the groups to break at the same time.

A draft group meeting schedule is already available at: https://www.w3.org/2024/05/tpac2024-schedule-20240523.html.
Your meeting requests will be added to the available slots.
We then ask you to discuss within your group(s) and let us know via the form below by *10 June at the latest*:

https://www.w3.org/2002/09/wbs/1/CGS-TPAC2024/

Note that a few Community Groups already submitted their requests. They have been added to the draft schedule.

We thank you in advance for your input to plan a successful hybrid event!

Alexandra Lacourba
W3C Global Events Coordinator

**Comment by besteves4** [comment]
If there's interest in having an ODRL meeting at TPAC, it would be nice to have on the agenda some time to discuss the alignment with DPV towards publishing a joint report (I'm leading this work and tracking it in #46). I will give an update on the status of said alignment in ODRL's July meeting.

**Comment by riannella** [comment]
@besteves4 Do you know if the DPV CG will be meeting at TPAC?

**Comment by besteves4** [comment]
Nothing is set in stone, but we have been discussing at least an online session. Looping in @coolharsh55 so he is aware of the discussions on the ODRL side as well.

**Comment by coolharsh55** [comment]
Hi. Thanks for this. DPVCG doesn't have a TPAC slot. If ODRL CG is meeting online, I can attend.
