### ISSUE TITLE
Section 2.6

### ISSUE THREAD

**Issue by joshcornejo** [w3c/odrl#62]
Text:

Explicit sub-properties of the abstract _relation_, _relation_ and _failure_ properties must be used, the choice depending on the subclass of Rule in question.

I think there is a mistake here: "**abstract _relation_, _relation_**", or needs further clarification (not sure why "relation" is twice).

Also as I pasted the text, Grammarly recommended removing "the choice" as it is redundant in the sentence.

**Comment by riannella** [comment]
Thanks Josh...move to POE GitHub for processing: https://github.com/w3c/poe/issues/313
